language: java
jdk:
  - oraclejdk11
  - openjdk11
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - os: windows
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install jdk11; fi
script:
  - mvn verify
