trigger:
- master

pr:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'
    jdk11:
      jdk_version: "1.11"
    jdk13:
      jdk_version: "1.13"

pool:
  vmImage: $(imageName)


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx128m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(jdk_version)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'verify'
