image: maven:3-jdk-10-slim

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn --batch-mode verify
          - ls -lh target/dist/hosh.jar
          - java -jar target/dist/hosh.jar  --version
